apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener.fullname" . }}-db-creds
type: Opaque
stringData:
  dbHost: {{ .Values.secret.dbHost | quote }}
  dbName: {{ .Values.secret.dbName | quote }}
  dbUsername: {{ .Values.secret.dbUsername | quote }}
  dbPassword: {{ .Values.secret.dbPassword | quote }}
