apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  labels:
    app: url-shortener
spec:
  replicas: 2 # Start with 2 replicas for high availability
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: your-dockerhub-username/url-shortener:latest # Will be patched by Kustomize overlay
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: url-shortener-db-creds
              key: db_host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: url-shortener-db-creds
              key: db_name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: url-shortener-db-creds
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: url-shortener-db-creds
              key: db_password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: url-shortener-config
              key: redis_host
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 15
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
