apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-db-creds
type: Opaque
stringData: # Use stringData for clear text, Kubernetes will base64 encode it
  db_host: postgresql-service # Assuming a PostgreSQL service named 'postgresql-service'
  db_name: url_shortener_db
  db_username: user
  db_password: password
